name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GOPRIVATE: "github.com/spinkube/spin-operator"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22.x"

    - name: Setup Private Git Repo Access
      run: echo "machine github.com login bacongobbler password ${GITHUB_TOKEN}" > $HOME/.netrc
      env:
        GITHUB_TOKEN: ${{ secrets.SPINKUBE_GITHUB_ACCESS_TOKEN }}

    - name: Build
      run: go build -o spin-plugin-k8s main.go

    - name: Run tests
      run: go test ./...
